[[language]]
name = "go"
language-servers = ["gopls"]
auto-format = true

[language-server.gopls]
command = "gopls"

[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[[language]]
name = "python"
language-servers = ["ruff", "pyright"]
formatter = { command = "ruff", args = ["format", "-"] }
auto-format = true

[[language]]
name = "typescript"
#scope = "source.ts"
language-servers = ["typescript-language-server"]
formatter = { command = "prettier", args = ["--stdin-filepath", "{file}"] }
auto-format = true

[language-server.typescript-language-server]
command = "typescript-language-server"
args = ["--stdio"]
